import { useEffect, useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { Check, Download, Eye, FileText, Plus, Save, Trash2 } from "lucide-react";
import ResumeTemplate from "../components/ResumeTemplate";

const starter = { personalInfo: { firstName: "Maya", lastName: "Patel", title: "Product Designer", email: "maya.patel@email.com", phone: "+1 (415) 555-0138", location: "San Francisco, CA", linkedin: "linkedin.com/in/mayapatel", website: "mayapatel.design" }, summary: "Product designer with 6+ years of experience turning complex problems into clear, delightful digital experiences. Skilled at partnering with product and engineering teams to ship accessible products that people love to use.", experience: [{ id: 1, company: "Northstar Labs", position: "Senior Product Designer", location: "San Francisco, CA", startDate: "2022-03", endDate: "Present", current: true, responsibilities: ["Led end-to-end design for a B2B platform used by 40k+ monthly users", "Built a shared design system that reduced delivery time by 25%", "Mentored two designers and facilitated customer research"] }], education: [{ id: 1, institution: "California College of the Arts", degree: "BFA", field: "Interaction Design", startDate: "2015-09", endDate: "2019-05", gpa: "3.8" }], skills: ["Figma", "Design systems", "User research", "Prototyping", "Accessibility"], certifications: [] };
const templates = ["modern", "minimalist", "sidebar", "academic", "creative", "executive"];
const labels = { modern: "Modern", minimalist: "Minimal", sidebar: "Sidebar", academic: "Academic", creative: "Creative", executive: "Executive" };
const palette = { modern: "#2563eb", minimalist: "#18212f", sidebar: "#087f5b", academic: "#18324b", creative: "#7c3aed", executive: "#18324b" };
const copy = (value) => JSON.parse(JSON.stringify(value));
const queryTemplate = (value) => { const s = (value || "").toLowerCase(); return s.includes("academic") ? "academic" : s.includes("creative") ? "creative" : s.includes("corporate") || s.includes("executive") ? "executive" : s.includes("minimal") ? "minimalist" : s.includes("sidebar") ? "sidebar" : "modern"; };
function Field({ label, value, onChange, type = "text" }) { return <label className="builder-field"><span>{label}</span><input type={type} value={value || ""} onChange={(e) => onChange(e.target.value)} /></label>; }

export default function ResumeBuilder() {
  const [params] = useSearchParams(); const initial = queryTemplate(params.get("template"));
  const [data, setData] = useState(() => { try { const saved = JSON.parse(localStorage.getItem("resume-builder-data")); return saved ? { ...copy(starter), ...saved, personalInfo: { ...starter.personalInfo, ...saved.personalInfo } } : copy(starter); } catch { return copy(starter); } });
  const [template, setTemplate] = useState(initial); const [color, setColor] = useState(palette[initial]); const [section, setSection] = useState("personal"); const [preview, setPreview] = useState(false); const [saved, setSaved] = useState(false);
  useEffect(() => localStorage.setItem("resume-builder-data", JSON.stringify(data)), [data]);
  const complete = useMemo(() => Math.round([data.personalInfo.firstName, data.personalInfo.lastName, data.personalInfo.email, data.personalInfo.title, data.summary, data.experience.length, data.education.length, data.skills.length].filter(Boolean).length / 8 * 100), [data]);
  const personal = (key, value) => setData((d) => ({ ...d, personalInfo: { ...d.personalInfo, [key]: value } }));
  const update = (collection, id, key, value) => setData((d) => ({ ...d, [collection]: d[collection].map((item) => item.id === id ? { ...item, [key]: value } : item) }));
  const save = () => { localStorage.setItem("resume-builder-data", JSON.stringify(data)); setSaved(true); setTimeout(() => setSaved(false), 2000); };
  const print = () => { document.title = `${data.personalInfo.firstName || "My"} ${data.personalInfo.lastName || "Resume"} - CV`; window.print(); };
  const add = (collection, item) => setData((d) => ({ ...d, [collection]: [...d[collection], { id: Date.now(), ...item }] }));
  const remove = (collection, id) => setData((d) => ({ ...d, [collection]: d[collection].filter((item) => item.id !== id) }));
  const form = () => { if (section === "personal") return <section><div className="section-heading"><div><p className="eyebrow">01 / About you</p><h2>Personal information</h2></div></div><div className="form-grid">{[["First name","firstName"],["Last name","lastName"],["Professional title","title"],["Email","email"],["Phone","phone"],["Location","location"],["LinkedIn","linkedin"],["Website","website"]].map(([label,key]) => <Field key={key} label={label} value={data.personalInfo[key]} onChange={(v) => personal(key,v)} type={key === "email" ? "email" : "text"}/>)}</div></section>;
    if (section === "summary") return <section><p className="eyebrow">02 / Your pitch</p><h2>Professional summary</h2><p className="helper">Write a clear 2–4 sentence introduction tailored to the job you want.</p><textarea className="summary-input" value={data.summary} onChange={(e) => setData({ ...data, summary: e.target.value })} maxLength={600}/><div className="char-count">{data.summary.length} / 600</div></section>;
    if (section === "skills") return <section><p className="eyebrow">05 / Your toolkit</p><h2>Skills</h2><p className="helper">Use commas between skills. Keep only the skills most relevant to the role.</p><textarea className="summary-input skills-input" value={data.skills.join(", ")} onChange={(e) => setData({ ...data, skills: e.target.value.split(",").map((x) => x.trim()).filter(Boolean) })}/></section>;
    if (section === "certifications") return <section><div className="section-heading"><div><p className="eyebrow">06 / Credentials</p><h2>Certifications</h2></div><button className="add-btn" onClick={() => add("certifications", { name: "", issuer: "", date: "" })}><Plus size={16}/> Add</button></div>{(data.certifications || []).map((x) => <div className="repeat-card" key={x.id}><button className="delete-btn" onClick={() => remove("certifications",x.id)}><Trash2 size={15}/></button><div className="form-grid"><Field label="Certification" value={x.name} onChange={(v) => update("certifications",x.id,"name",v)}/><Field label="Issuer" value={x.issuer} onChange={(v) => update("certifications",x.id,"issuer",v)}/><Field label="Date" type="month" value={x.date} onChange={(v) => update("certifications",x.id,"date",v)}/></div></div>)}</section>;
    const collection = section === "experience" ? "experience" : "education"; const isExp = collection === "experience"; const items = data[collection]; return <section><div className="section-heading"><div><p className="eyebrow">{isExp ? "03 / Your impact" : "04 / Your foundation"}</p><h2>{isExp ? "Work experience" : "Education"}</h2></div><button className="add-btn" onClick={() => add(collection, isExp ? { company:"", position:"", location:"", startDate:"", endDate:"", current:false, responsibilities:[""] } : { institution:"", degree:"", field:"", startDate:"", endDate:"", gpa:"" })}><Plus size={16}/> Add {isExp ? "role" : "school"}</button></div>{items.map((x) => <div className="repeat-card" key={x.id}><button className="delete-btn" onClick={() => remove(collection,x.id)}><Trash2 size={15}/></button><div className="form-grid">{(isExp ? [["Job title","position"],["Company","company"],["Location","location"],["Start date","startDate"],["End date","endDate"]] : [["Institution","institution"],["Degree","degree"],["Field of study","field"],["Start date","startDate"],["End date","endDate"],["GPA","gpa"]]).map(([label,key]) => <Field key={key} label={label} value={x[key]} onChange={(v) => update(collection,x.id,key,v)} type={key.toLowerCase().includes("date") ? "month" : "text"}/>)}</div>{isExp && <><label className="check-field"><input type="checkbox" checked={x.current} onChange={(e) => update(collection,x.id,"current",e.target.checked)}/> I currently work here</label><label className="builder-field"><span>Key achievements · one per line</span><textarea value={(x.responsibilities || []).join("\n")} onChange={(e) => update(collection,x.id,"responsibilities",e.target.value.split("\n"))}/></label></>}</div>)}</section>; };
  const sectionTabs = [["personal","Personal info"],["summary","Summary"],["experience","Experience"],["education","Education"],["skills","Skills"],["certifications","Certifications"]];
  return <div className="builder-shell"><header className="builder-header"><Link to="/" className="brand"><span className="brand-mark"><FileText size={19}/></span><span>Resume<span>Forge</span></span></Link><div className="builder-status"><span className="save-dot"/>{saved ? "Saved just now" : "Auto-saved locally"}</div><div className="builder-actions"><button className="ghost-btn" onClick={() => setPreview(!preview)}><Eye size={17}/> {preview ? "Edit resume" : "Preview"}</button><button className="primary-btn" onClick={save}><Save size={17}/> Save resume</button></div></header><main className="builder-main"><aside className={`editor-panel ${preview ? "editor-hidden" : ""}`}><div className="editor-intro"><p className="eyebrow">Resume workspace</p><h1>Build your story.</h1><p>Create a professional CV ready to send to employers.</p><div className="progress-line"><div style={{ width: `${complete}%` }}/></div><small>{complete}% complete</small></div><nav className="section-tabs">{sectionTabs.map(([id,label]) => <button className={section === id ? "active" : ""} onClick={() => setSection(id)} key={id}>{label}{section === id && <Check size={15}/>}</button>)}</nav><div className="form-content">{form()}</div></aside><section className={`preview-panel ${preview ? "preview-full" : ""}`}><div className="preview-toolbar"><div><p className="eyebrow">Live preview</p><span>A4 document · ready to export</span></div><div className="template-picker">{templates.map((id) => <button className={template === id ? "selected" : ""} onClick={() => { setTemplate(id); setColor(palette[id]); }} key={id}>{labels[id]}</button>)}</div><label className="color-picker" title="Choose accent color"><span>Accent</span><input aria-label="Choose resume color" type="color" value={color} onChange={(e) => setColor(e.target.value)}/></label><button className="download-btn" onClick={print}><Download size={16}/> Export PDF</button></div><div className="paper-wrap"><div className="paper"><ResumeTemplate variant={template} colorScheme={color} resumeData={data}/></div></div></section></main></div>;
}
